language: php

php: 7.3

script:
  - echo ""

before_script:
  - composer self-update
  - composer require phing/phing:2.*
  #- composer install --no-dev --prefer-dist --optimize-autoloader
  - mv app/config/sample.local.neon app/config/local.neon
  - rm -f app/config/ci.local.neon
  #- zip -r SRS app backup log migrations temp vendor www .htaccess README.md

script:
    - vendor/bin/phing
